name: azadel_daily
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  provider: ^6.1.1
  url_launcher: ^6.2.0
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_messaging: ^16.0.3


  weather_package:
    path: ../weather_package
  flutter_bloc: ^9.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.14.4



flutter:


  uses-material-design: true


  assets:
    - aap_icon.png


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "aap_icon.png"  # ‚Üê Chemin vers ton logo
  remove_alpha_ios: true  

